---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-7.1
    driver:
      customize:
        memory: 350


suites:
  - name: default
    run_list:
      - recipe[jenkins-job::default]
    attributes:
